// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package entity

import (
	"time"

	"gorm.io/gorm"
)

const TableNameAttendance = "attendances"

// Attendance mapped from table <attendances>
type Attendance struct {
	ID            int64          `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	UUID          string         `gorm:"column:uuid;not null" json:"uuid"`
	Action        string         `gorm:"column:action;not null" json:"action"`
	Remark        string         `gorm:"column:remark" json:"remark"`
	UserID        int64          `gorm:"column:user_id;not null" json:"user_id"`
	StoreID       int64          `gorm:"column:store_id;not null" json:"store_id"`
	DutyID        int64          `gorm:"column:duty_id" json:"duty_id"`
	CreatedAt     time.Time      `gorm:"column:created_at" json:"created_at"`
	UpdatedAt     time.Time      `gorm:"column:updated_at" json:"updated_at"`
	RequireRemark bool           `gorm:"column:require_remark;not null" json:"require_remark"`
	DeletedAt     gorm.DeletedAt `gorm:"column:deleted_at" json:"deleted_at"`
}

// TableName Attendance's table name
func (*Attendance) TableName() string {
	return TableNameAttendance
}
