// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package entity

import (
	"time"

	"gorm.io/gorm"
)

const TableNameAttendanceAdjustment = "attendance_adjustments"

// AttendanceAdjustment mapped from table <attendance_adjustments>
type AttendanceAdjustment struct {
	ID            int64          `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	UUID          string         `gorm:"column:uuid;not null" json:"uuid"`
	Status        string         `gorm:"column:status;not null;default:pending" json:"status"`
	IsActive      bool           `gorm:"column:is_active;not null" json:"is_active"`
	AdjustedTime  time.Time      `gorm:"column:adjusted_time;not null" json:"adjusted_time"`
	AttendanceID  int64          `gorm:"column:attendance_id;not null" json:"attendance_id"`
	CreatedBy     int64          `gorm:"column:created_by" json:"created_by"`
	ConfirmedBy   int64          `gorm:"column:confirmed_by" json:"confirmed_by"`
	ConfirmTime   time.Time      `gorm:"column:confirm_time" json:"confirm_time"`
	Remark        string         `gorm:"column:remark" json:"remark"`
	CreatedAt     time.Time      `gorm:"column:created_at" json:"created_at"`
	UpdatedAt     time.Time      `gorm:"column:updated_at" json:"updated_at"`
	DeletedAt     gorm.DeletedAt `gorm:"column:deleted_at" json:"deleted_at"`
	ConfirmRemark string         `gorm:"column:confirm_remark" json:"confirm_remark"`
}

// TableName AttendanceAdjustment's table name
func (*AttendanceAdjustment) TableName() string {
	return TableNameAttendanceAdjustment
}
