// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package entity

import (
	"time"

	"gorm.io/gorm"
)

const TableNameCashExpense = "cash_expenses"

// CashExpense mapped from table <cash_expenses>
type CashExpense struct {
	ID          int64          `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	UUID        string         `gorm:"column:uuid;not null" json:"uuid"`
	StoreID     int64          `gorm:"column:store_id;not null" json:"store_id"`
	Category    string         `gorm:"column:category" json:"category"`
	Description string         `gorm:"column:description;not null" json:"description"`
	Price       float64        `gorm:"column:price" json:"price"`
	Remark      string         `gorm:"column:remark" json:"remark"`
	ApplyDate   time.Time      `gorm:"column:apply_date;not null" json:"apply_date"`
	UserID      int64          `gorm:"column:user_id;not null" json:"user_id"`
	DeletedAt   gorm.DeletedAt `gorm:"column:deleted_at" json:"deleted_at"`
	CreatedAt   time.Time      `gorm:"column:created_at" json:"created_at"`
	UpdatedAt   time.Time      `gorm:"column:updated_at" json:"updated_at"`
}

// TableName CashExpense's table name
func (*CashExpense) TableName() string {
	return TableNameCashExpense
}
