// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package entity

import (
	"time"

	"gorm.io/gorm"
)

const TableNameCashExpenseAttachment = "cash_expense_attachments"

// CashExpenseAttachment mapped from table <cash_expense_attachments>
type CashExpenseAttachment struct {
	ID            int64          `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	CashExpenseID int64          `gorm:"column:cash_expense_id" json:"cash_expense_id"`
	URL           string         `gorm:"column:url;not null" json:"url"`
	DeletedAt     gorm.DeletedAt `gorm:"column:deleted_at" json:"deleted_at"`
	CreatedAt     time.Time      `gorm:"column:created_at" json:"created_at"`
	UpdatedAt     time.Time      `gorm:"column:updated_at" json:"updated_at"`
}

// TableName CashExpenseAttachment's table name
func (*CashExpenseAttachment) TableName() string {
	return TableNameCashExpenseAttachment
}
