// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package entity

import (
	"time"

	"gorm.io/gorm"
)

const TableNameDeliveryType = "delivery_types"

// DeliveryType mapped from table <delivery_types>
type DeliveryType struct {
	ID        int32          `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Name      string         `gorm:"column:name;not null" json:"name"`
	Type      string         `gorm:"column:type;not null;default:pickup" json:"type"`
	Location  string         `gorm:"column:location;not null" json:"location"`
	Gps       string         `gorm:"column:gps" json:"gps"`
	DeletedAt gorm.DeletedAt `gorm:"column:deleted_at" json:"deleted_at"`
	CreatedAt time.Time      `gorm:"column:created_at" json:"created_at"`
	UpdatedAt time.Time      `gorm:"column:updated_at" json:"updated_at"`
}

// TableName DeliveryType's table name
func (*DeliveryType) TableName() string {
	return TableNameDeliveryType
}
