// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package entity

import (
	"time"

	"gorm.io/gorm"
)

const TableNameDuty = "duties"

// Duty mapped from table <duties>
type Duty struct {
	ID         int64          `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	UserID     int64          `gorm:"column:user_id;not null" json:"user_id"`
	UUID       string         `gorm:"column:uuid;not null" json:"uuid"`
	StoreID    int64          `gorm:"column:store_id;not null" json:"store_id"`
	IsPublic   bool           `gorm:"column:is_public;not null" json:"is_public"`
	FromTime   time.Time      `gorm:"column:from_time;not null" json:"from_time"`
	ToTime     time.Time      `gorm:"column:to_time;not null" json:"to_time"`
	CreatedAt  time.Time      `gorm:"column:created_at" json:"created_at"`
	UpdatedAt  time.Time      `gorm:"column:updated_at" json:"updated_at"`
	DeletedAt  gorm.DeletedAt `gorm:"column:deleted_at" json:"deleted_at"`
	RoleID     int32          `gorm:"column:role_id" json:"role_id"`
	HourlyWage float64        `gorm:"column:hourly_wage" json:"hourly_wage"`
	RoleWage   int32          `gorm:"column:role_wage" json:"role_wage"`
}

// TableName Duty's table name
func (*Duty) TableName() string {
	return TableNameDuty
}
