// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package entity

import (
	"time"
)

const TableNameGoodReceivedNoteItem = "good_received_note_items"

// GoodReceivedNoteItem mapped from table <good_received_note_items>
type GoodReceivedNoteItem struct {
	ID                 int64     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	GoodReceivedNoteID int64     `gorm:"column:good_received_note_id;not null" json:"good_received_note_id"`
	RawMaterialID      int64     `gorm:"column:raw_material_id" json:"raw_material_id"`
	Qty                float64   `gorm:"column:qty;not null" json:"qty"`
	Remark             string    `gorm:"column:remark" json:"remark"`
	CreatedBy          int64     `gorm:"column:created_by" json:"created_by"`
	CreatedAt          time.Time `gorm:"column:created_at" json:"created_at"`
	UpdatedAt          time.Time `gorm:"column:updated_at" json:"updated_at"`
}

// TableName GoodReceivedNoteItem's table name
func (*GoodReceivedNoteItem) TableName() string {
	return TableNameGoodReceivedNoteItem
}
