// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package entity

import (
	"time"

	"gorm.io/gorm"
)

const TableNameGoodReceivedNote = "good_received_notes"

// GoodReceivedNote mapped from table <good_received_notes>
type GoodReceivedNote struct {
	ID               int64          `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	UUID             string         `gorm:"column:uuid;not null" json:"uuid"`
	DisplayID        string         `gorm:"column:display_id" json:"display_id"`
	Status           string         `gorm:"column:status" json:"status"`
	PurchaseOrderID  int64          `gorm:"column:purchase_order_id" json:"purchase_order_id"`
	SupplierID       int64          `gorm:"column:supplier_id" json:"supplier_id"`
	GoodReceivedDate time.Time      `gorm:"column:good_received_date" json:"good_received_date"`
	Remark           string         `gorm:"column:remark" json:"remark"`
	CreatedBy        int64          `gorm:"column:created_by" json:"created_by"`
	ConfirmedBy      int64          `gorm:"column:confirmed_by" json:"confirmed_by"`
	ConfirmedAt      time.Time      `gorm:"column:confirmed_at" json:"confirmed_at"`
	DeletedAt        gorm.DeletedAt `gorm:"column:deleted_at" json:"deleted_at"`
	CreatedAt        time.Time      `gorm:"column:created_at" json:"created_at"`
	UpdatedAt        time.Time      `gorm:"column:updated_at" json:"updated_at"`
	TenantID         int64          `gorm:"column:tenant_id" json:"tenant_id"`
	Type             string         `gorm:"column:type;not null;default:received" json:"type"`
}

// TableName GoodReceivedNote's table name
func (*GoodReceivedNote) TableName() string {
	return TableNameGoodReceivedNote
}
