// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package entity

import (
	"time"

	"gorm.io/gorm"
)

const TableNameGoodReceivedItemsTransferNote = "good_received_items_transfer_notes"

// GoodReceivedItemsTransferNote mapped from table <good_received_items_transfer_notes>
type GoodReceivedItemsTransferNote struct {
	ID                     int64          `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Qty                    float64        `gorm:"column:qty;not null" json:"qty"`
	GoodReceivedNoteItemID int64          `gorm:"column:good_received_note_item_id;not null" json:"good_received_note_item_id"`
	WarehouseID            int64          `gorm:"column:warehouse_id;not null" json:"warehouse_id"`
	DeletedAt              gorm.DeletedAt `gorm:"column:deleted_at" json:"deleted_at"`
	CreatedAt              time.Time      `gorm:"column:created_at" json:"created_at"`
	UpdatedAt              time.Time      `gorm:"column:updated_at" json:"updated_at"`
	WarehouseAreaID        int64          `gorm:"column:warehouse_area_id" json:"warehouse_area_id"`
}

// TableName GoodReceivedItemsTransferNote's table name
func (*GoodReceivedItemsTransferNote) TableName() string {
	return TableNameGoodReceivedItemsTransferNote
}
