// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package entity

import (
	"time"

	"gorm.io/gorm"
)

const TableNameLeafe = "leaves"

// Leafe mapped from table <leaves>
type Leafe struct {
	ID                  int64          `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	UUID                string         `gorm:"column:uuid;not null" json:"uuid"`
	Name                string         `gorm:"column:name;not null" json:"name"`
	Description         string         `gorm:"column:description;not null" json:"description"`
	HasPay              bool           `gorm:"column:has_pay;not null;default:1" json:"has_pay"`
	EmploymentCondition string         `gorm:"column:employment_condition;not null;default:any" json:"employment_condition"`
	EmploymentMonths    int32          `gorm:"column:employment_months;not null" json:"employment_months"`
	BeforeDays          int32          `gorm:"column:before_days;not null" json:"before_days"`
	Quota               int32          `gorm:"column:quota;not null" json:"quota"`
	Unit                string         `gorm:"column:unit;not null;default:full-day" json:"unit"`
	RefillPeriod        string         `gorm:"column:refill_period" json:"refill_period"`
	Expire              string         `gorm:"column:expire;not null;default:period" json:"expire"`
	Forward             int32          `gorm:"column:forward;not null" json:"forward"`
	ForwardUnit         string         `gorm:"column:forward_unit;not null;default:month" json:"forward_unit"`
	ForwardMax          int32          `gorm:"column:forward_max;not null" json:"forward_max"`
	DeletedAt           gorm.DeletedAt `gorm:"column:deleted_at" json:"deleted_at"`
	CreatedAt           time.Time      `gorm:"column:created_at" json:"created_at"`
	UpdatedAt           time.Time      `gorm:"column:updated_at" json:"updated_at"`
	ManagedBy           string         `gorm:"column:managed_by;default:manager" json:"managed_by"`
	OtCount             bool           `gorm:"column:ot_count;not null" json:"ot_count"`
}

// TableName Leafe's table name
func (*Leafe) TableName() string {
	return TableNameLeafe
}
