// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package entity

import (
	"time"
)

const TableNameLeaveRole = "leave_role"

// LeaveRole mapped from table <leave_role>
type LeaveRole struct {
	ID        int64     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	LeaveID   int64     `gorm:"column:leave_id;not null" json:"leave_id"`
	RoleID    int32     `gorm:"column:role_id;not null" json:"role_id"`
	CreatedAt time.Time `gorm:"column:created_at" json:"created_at"`
	UpdatedAt time.Time `gorm:"column:updated_at" json:"updated_at"`
}

// TableName LeaveRole's table name
func (*LeaveRole) TableName() string {
	return TableNameLeaveRole
}
