// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package entity

import (
	"time"

	"gorm.io/gorm"
)

const TableNameMember = "members"

// Member mapped from table <members>
type Member struct {
	ID                    int64          `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Name                  string         `gorm:"column:name;not null" json:"name"`
	Email                 string         `gorm:"column:email" json:"email"`
	EmailVerifiedAt       time.Time      `gorm:"column:email_verified_at" json:"email_verified_at"`
	Birthday              time.Time      `gorm:"column:birthday" json:"birthday"`
	Referral              string         `gorm:"column:referral" json:"referral"`
	Passkit               string         `gorm:"column:passkit" json:"passkit"`
	RememberToken         string         `gorm:"column:remember_token" json:"remember_token"`
	CreatedAt             time.Time      `gorm:"column:created_at" json:"created_at"`
	UpdatedAt             time.Time      `gorm:"column:updated_at" json:"updated_at"`
	DeletedAt             gorm.DeletedAt `gorm:"column:deleted_at" json:"deleted_at"`
	MobilePhone           string         `gorm:"column:mobile_phone;not null" json:"mobile_phone"`
	MobilePhoneVerifiedAt time.Time      `gorm:"column:mobile_phone_verified_at" json:"mobile_phone_verified_at"`
	Target                string         `gorm:"column:target;not null;default:moomoo" json:"target"`
	LastName              string         `gorm:"column:last_name" json:"last_name"`
	Gps                   string         `gorm:"column:gps" json:"gps"`
	IP                    string         `gorm:"column:ip" json:"ip"`
	DeviceID              string         `gorm:"column:deviceId" json:"deviceId"`
	LastToken             string         `gorm:"column:last_token" json:"last_token"`
}

// TableName Member's table name
func (*Member) TableName() string {
	return TableNameMember
}
