// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package entity

import (
	"time"

	"gorm.io/gorm"
)

const TableNameMessageAttachment = "message_attachments"

// MessageAttachment mapped from table <message_attachments>
type MessageAttachment struct {
	ID        int64          `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	MessageID int64          `gorm:"column:message_id" json:"message_id"`
	URL       string         `gorm:"column:url;not null" json:"url"`
	DeletedAt gorm.DeletedAt `gorm:"column:deleted_at" json:"deleted_at"`
	CreatedAt time.Time      `gorm:"column:created_at" json:"created_at"`
	UpdatedAt time.Time      `gorm:"column:updated_at" json:"updated_at"`
}

// TableName MessageAttachment's table name
func (*MessageAttachment) TableName() string {
	return TableNameMessageAttachment
}
