// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package entity

import (
	"time"

	"gorm.io/gorm"
)

const TableNameMessage = "messages"

// Message mapped from table <messages>
type Message struct {
	ID          int64          `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	UUID        string         `gorm:"column:uuid;not null" json:"uuid"`
	Title       string         `gorm:"column:title" json:"title"`
	Content     string         `gorm:"column:content" json:"content"`
	CreatedBy   int64          `gorm:"column:created_by" json:"created_by"`
	DeletedAt   gorm.DeletedAt `gorm:"column:deleted_at" json:"deleted_at"`
	CreatedAt   time.Time      `gorm:"column:created_at" json:"created_at"`
	UpdatedAt   time.Time      `gorm:"column:updated_at" json:"updated_at"`
	TenantID    int64          `gorm:"column:tenant_id" json:"tenant_id"`
	PushReceipt string         `gorm:"column:push_receipt" json:"push_receipt"`
	Data        string         `gorm:"column:data" json:"data"`
}

// TableName Message's table name
func (*Message) TableName() string {
	return TableNameMessage
}
