// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package entity

import (
	"time"
)

const TableNameMessageRole = "message_role"

// MessageRole mapped from table <message_role>
type MessageRole struct {
	ID        int64     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	MessageID int64     `gorm:"column:message_id" json:"message_id"`
	RoleID    int32     `gorm:"column:role_id" json:"role_id"`
	CreatedAt time.Time `gorm:"column:created_at" json:"created_at"`
	UpdatedAt time.Time `gorm:"column:updated_at" json:"updated_at"`
}

// TableName MessageRole's table name
func (*MessageRole) TableName() string {
	return TableNameMessageRole
}
