// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package entity

import (
	"time"
)

const TableNameMessageStore = "message_store"

// MessageStore mapped from table <message_store>
type MessageStore struct {
	ID        int64     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	MessageID int64     `gorm:"column:message_id" json:"message_id"`
	StoreID   int64     `gorm:"column:store_id" json:"store_id"`
	CreatedAt time.Time `gorm:"column:created_at" json:"created_at"`
	UpdatedAt time.Time `gorm:"column:updated_at" json:"updated_at"`
}

// TableName MessageStore's table name
func (*MessageStore) TableName() string {
	return TableNameMessageStore
}
