// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package entity

import (
	"time"
)

const TableNameMessageUser = "message_user"

// MessageUser mapped from table <message_user>
type MessageUser struct {
	ID        int64     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	MessageID int64     `gorm:"column:message_id" json:"message_id"`
	UserID    int64     `gorm:"column:user_id" json:"user_id"`
	CreatedAt time.Time `gorm:"column:created_at" json:"created_at"`
	UpdatedAt time.Time `gorm:"column:updated_at" json:"updated_at"`
	ReadAt    time.Time `gorm:"column:read_at" json:"read_at"`
}

// TableName MessageUser's table name
func (*MessageUser) TableName() string {
	return TableNameMessageUser
}
