// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package entity

import (
	"time"
)

const TableNameOauthAccessToken = "oauth_access_tokens"

// OauthAccessToken mapped from table <oauth_access_tokens>
type OauthAccessToken struct {
	ID        string    `gorm:"column:id;primaryKey" json:"id"`
	UserID    int64     `gorm:"column:user_id" json:"user_id"`
	ClientID  int64     `gorm:"column:client_id;not null" json:"client_id"`
	Name      string    `gorm:"column:name" json:"name"`
	Scopes    string    `gorm:"column:scopes" json:"scopes"`
	Revoked   bool      `gorm:"column:revoked;not null" json:"revoked"`
	CreatedAt time.Time `gorm:"column:created_at" json:"created_at"`
	UpdatedAt time.Time `gorm:"column:updated_at" json:"updated_at"`
	ExpiresAt time.Time `gorm:"column:expires_at" json:"expires_at"`
}

// TableName OauthAccessToken's table name
func (*OauthAccessToken) TableName() string {
	return TableNameOauthAccessToken
}
