// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package entity

import (
	"time"
)

const TableNameOauthClient = "oauth_clients"

// OauthClient mapped from table <oauth_clients>
type OauthClient struct {
	ID                   int64     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	UserID               int64     `gorm:"column:user_id" json:"user_id"`
	Name                 string    `gorm:"column:name;not null" json:"name"`
	Secret               string    `gorm:"column:secret" json:"secret"`
	Redirect             string    `gorm:"column:redirect;not null" json:"redirect"`
	PersonalAccessClient bool      `gorm:"column:personal_access_client;not null" json:"personal_access_client"`
	PasswordClient       bool      `gorm:"column:password_client;not null" json:"password_client"`
	Revoked              bool      `gorm:"column:revoked;not null" json:"revoked"`
	CreatedAt            time.Time `gorm:"column:created_at" json:"created_at"`
	UpdatedAt            time.Time `gorm:"column:updated_at" json:"updated_at"`
}

// TableName OauthClient's table name
func (*OauthClient) TableName() string {
	return TableNameOauthClient
}
