// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package entity

import (
	"time"
)

const TableNameOauthPersonalAccessClient = "oauth_personal_access_clients"

// OauthPersonalAccessClient mapped from table <oauth_personal_access_clients>
type OauthPersonalAccessClient struct {
	ID        int64     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	ClientID  int64     `gorm:"column:client_id;not null" json:"client_id"`
	CreatedAt time.Time `gorm:"column:created_at" json:"created_at"`
	UpdatedAt time.Time `gorm:"column:updated_at" json:"updated_at"`
}

// TableName OauthPersonalAccessClient's table name
func (*OauthPersonalAccessClient) TableName() string {
	return TableNameOauthPersonalAccessClient
}
