// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package entity

import (
	"time"
)

const TableNameOauthRefreshToken = "oauth_refresh_tokens"

// OauthRefreshToken mapped from table <oauth_refresh_tokens>
type OauthRefreshToken struct {
	ID            string    `gorm:"column:id;primaryKey" json:"id"`
	AccessTokenID string    `gorm:"column:access_token_id;not null" json:"access_token_id"`
	Revoked       bool      `gorm:"column:revoked;not null" json:"revoked"`
	ExpiresAt     time.Time `gorm:"column:expires_at" json:"expires_at"`
}

// TableName OauthRefreshToken's table name
func (*OauthRefreshToken) TableName() string {
	return TableNameOauthRefreshToken
}
