// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package entity

import (
	"time"
)

const TableNameOtp = "otp"

// Otp mapped from table <otp>
type Otp struct {
	ID        int32     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Token     int32     `gorm:"column:token;not null" json:"token"`
	Module    string    `gorm:"column:module;not null" json:"module"`
	EntityID  string    `gorm:"column:entity_id;not null" json:"entity_id"`
	ExpiresOn time.Time `gorm:"column:expires_on;not null" json:"expires_on"`
	CreatedAt time.Time `gorm:"column:created_at" json:"created_at"`
	UpdatedAt time.Time `gorm:"column:updated_at" json:"updated_at"`
}

// TableName Otp's table name
func (*Otp) TableName() string {
	return TableNameOtp
}
