// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package entity

import (
	"time"

	"gorm.io/gorm"
)

const TableNamePasskitMemberActivity = "passkit_member_activities"

// PasskitMemberActivity mapped from table <passkit_member_activities>
type PasskitMemberActivity struct {
	ID              int64          `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Activity        string         `gorm:"column:activity;not null" json:"activity"`
	PasskitMemberID int64          `gorm:"column:passkit_member_id;not null" json:"passkit_member_id"`
	DeletedAt       gorm.DeletedAt `gorm:"column:deleted_at" json:"deleted_at"`
	CreatedAt       time.Time      `gorm:"column:created_at" json:"created_at"`
	UpdatedAt       time.Time      `gorm:"column:updated_at" json:"updated_at"`
}

// TableName PasskitMemberActivity's table name
func (*PasskitMemberActivity) TableName() string {
	return TableNamePasskitMemberActivity
}
