// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package entity

import (
	"time"
)

const TableNamePasswordReset = "password_resets"

// PasswordReset mapped from table <password_resets>
type PasswordReset struct {
	Email     string    `gorm:"column:email;not null" json:"email"`
	Token     string    `gorm:"column:token;not null" json:"token"`
	CreatedAt time.Time `gorm:"column:created_at" json:"created_at"`
}

// TableName PasswordReset's table name
func (*PasswordReset) TableName() string {
	return TableNamePasswordReset
}
