// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package entity

import (
	"time"

	"gorm.io/gorm"
)

const TableNamePermissionRole = "permission_role"

// PermissionRole mapped from table <permission_role>
type PermissionRole struct {
	ID           int32          `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	PermissionID int32          `gorm:"column:permission_id;not null" json:"permission_id"`
	RoleID       int32          `gorm:"column:role_id;not null" json:"role_id"`
	CreatedAt    time.Time      `gorm:"column:created_at" json:"created_at"`
	UpdatedAt    time.Time      `gorm:"column:updated_at" json:"updated_at"`
	DeletedAt    gorm.DeletedAt `gorm:"column:deleted_at" json:"deleted_at"`
}

// TableName PermissionRole's table name
func (*PermissionRole) TableName() string {
	return TableNamePermissionRole
}
