// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package entity

import (
	"time"

	"gorm.io/gorm"
)

const TableNamePosMenu = "pos_menus"

// PosMenu mapped from table <pos_menus>
type PosMenu struct {
	ID        int64          `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	UUID      string         `gorm:"column:uuid;not null" json:"uuid"`
	StoreID   int64          `gorm:"column:store_id;not null" json:"store_id"`
	Status    string         `gorm:"column:status;not null;default:Active" json:"status"`
	Name      string         `gorm:"column:name;not null" json:"name"`
	DeletedAt gorm.DeletedAt `gorm:"column:deleted_at" json:"deleted_at"`
	CreatedAt time.Time      `gorm:"column:created_at" json:"created_at"`
	UpdatedAt time.Time      `gorm:"column:updated_at" json:"updated_at"`
}

// TableName PosMenu's table name
func (*PosMenu) TableName() string {
	return TableNamePosMenu
}
