// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package entity

import (
	"time"

	"gorm.io/gorm"
)

const TableNamePosProductModifierOption = "pos_product_modifier_options"

// PosProductModifierOption mapped from table <pos_product_modifier_options>
type PosProductModifierOption struct {
	ID                   int64          `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	UUID                 string         `gorm:"column:uuid;not null" json:"uuid"`
	Name                 string         `gorm:"column:name;not null" json:"name"`
	AddOnPrice           float64        `gorm:"column:add_on_price;not null;default:0.00" json:"add_on_price"`
	DeletedAt            gorm.DeletedAt `gorm:"column:deleted_at" json:"deleted_at"`
	CreatedAt            time.Time      `gorm:"column:created_at" json:"created_at"`
	UpdatedAt            time.Time      `gorm:"column:updated_at" json:"updated_at"`
	MaxAllowed           int32          `gorm:"column:max_allowed" json:"max_allowed"`
	IsDefault            bool           `gorm:"column:is_default;not null" json:"is_default"`
	PosProductModifierID int64          `gorm:"column:pos_product_modifier_id;not null;default:1" json:"pos_product_modifier_id"`
}

// TableName PosProductModifierOption's table name
func (*PosProductModifierOption) TableName() string {
	return TableNamePosProductModifierOption
}
