// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package entity

import (
	"time"

	"gorm.io/gorm"
)

const TableNamePosProductComboOptionProduct = "pos_product_combo_option_products"

// PosProductComboOptionProduct mapped from table <pos_product_combo_option_products>
type PosProductComboOptionProduct struct {
	ID               int64          `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	UUID             string         `gorm:"column:uuid;not null" json:"uuid"`
	PosComboOptionID int64          `gorm:"column:pos_combo_option_id;not null" json:"pos_combo_option_id"`
	PosProductID     int64          `gorm:"column:pos_product_id" json:"pos_product_id"`
	PosCategoryID    int64          `gorm:"column:pos_category_id" json:"pos_category_id"`
	DeletedAt        gorm.DeletedAt `gorm:"column:deleted_at" json:"deleted_at"`
	CreatedAt        time.Time      `gorm:"column:created_at" json:"created_at"`
	UpdatedAt        time.Time      `gorm:"column:updated_at" json:"updated_at"`
	Discount         float64        `gorm:"column:discount;not null;default:0.00" json:"discount"`
	AddOnPrice       float64        `gorm:"column:add_on_price;not null;default:0.00" json:"add_on_price"`
	MaxAllowed       int32          `gorm:"column:max_allowed" json:"max_allowed"`
}

// TableName PosProductComboOptionProduct's table name
func (*PosProductComboOptionProduct) TableName() string {
	return TableNamePosProductComboOptionProduct
}
