// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package entity

import (
	"time"

	"gorm.io/gorm"
)

const TableNamePosProductType = "pos_product_types"

// PosProductType mapped from table <pos_product_types>
type PosProductType struct {
	ID        int64          `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	UUID      string         `gorm:"column:uuid;not null" json:"uuid"`
	Name      string         `gorm:"column:name;not null" json:"name"`
	Code      string         `gorm:"column:code" json:"code"`
	DeletedAt gorm.DeletedAt `gorm:"column:deleted_at" json:"deleted_at"`
	CreatedAt time.Time      `gorm:"column:created_at" json:"created_at"`
	UpdatedAt time.Time      `gorm:"column:updated_at" json:"updated_at"`
	StoreID   int64          `gorm:"column:store_id;not null;default:1" json:"store_id"`
}

// TableName PosProductType's table name
func (*PosProductType) TableName() string {
	return TableNamePosProductType
}
