// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package entity

import (
	"time"

	"gorm.io/gorm"
)

const TableNamePosSubProductTypesTranslation = "pos_sub_product_types_translations"

// PosSubProductTypesTranslation mapped from table <pos_sub_product_types_translations>
type PosSubProductTypesTranslation struct {
	ID               int64          `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	SubProductTypeID int64          `gorm:"column:sub_product_type_id" json:"sub_product_type_id"`
	Locale           string         `gorm:"column:locale;not null;default:en" json:"locale"`
	Name             string         `gorm:"column:name;not null" json:"name"`
	DeletedAt        gorm.DeletedAt `gorm:"column:deleted_at" json:"deleted_at"`
	CreatedAt        time.Time      `gorm:"column:created_at" json:"created_at"`
	UpdatedAt        time.Time      `gorm:"column:updated_at" json:"updated_at"`
}

// TableName PosSubProductTypesTranslation's table name
func (*PosSubProductTypesTranslation) TableName() string {
	return TableNamePosSubProductTypesTranslation
}
