// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package entity

import (
	"time"

	"gorm.io/gorm"
)

const TableNamePosCategoriesTranslation = "pos_categories_translations"

// PosCategoriesTranslation mapped from table <pos_categories_translations>
type PosCategoriesTranslation struct {
	ID          int64          `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	CategoryID  int64          `gorm:"column:category_id" json:"category_id"`
	Locale      string         `gorm:"column:locale;not null;default:en" json:"locale"`
	Name        string         `gorm:"column:name;not null" json:"name"`
	Description string         `gorm:"column:description;not null" json:"description"`
	DeletedAt   gorm.DeletedAt `gorm:"column:deleted_at" json:"deleted_at"`
	CreatedAt   time.Time      `gorm:"column:created_at" json:"created_at"`
	UpdatedAt   time.Time      `gorm:"column:updated_at" json:"updated_at"`
}

// TableName PosCategoriesTranslation's table name
func (*PosCategoriesTranslation) TableName() string {
	return TableNamePosCategoriesTranslation
}
