// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package entity

import (
	"time"

	"gorm.io/gorm"
)

const TableNamePosSubProductType = "pos_sub_product_types"

// PosSubProductType mapped from table <pos_sub_product_types>
type PosSubProductType struct {
	ID               int64          `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	UUID             string         `gorm:"column:uuid;not null" json:"uuid"`
	Name             string         `gorm:"column:name;not null" json:"name"`
	Code             string         `gorm:"column:code" json:"code"`
	PosProductTypeID int64          `gorm:"column:pos_product_type_id" json:"pos_product_type_id"`
	DeletedAt        gorm.DeletedAt `gorm:"column:deleted_at" json:"deleted_at"`
	CreatedAt        time.Time      `gorm:"column:created_at" json:"created_at"`
	UpdatedAt        time.Time      `gorm:"column:updated_at" json:"updated_at"`
}

// TableName PosSubProductType's table name
func (*PosSubProductType) TableName() string {
	return TableNamePosSubProductType
}
