// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package entity

import (
	"time"

	"gorm.io/gorm"
)

const TableNamePosProductsTranslation = "pos_products_translations"

// PosProductsTranslation mapped from table <pos_products_translations>
type PosProductsTranslation struct {
	ID          int64          `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	ProductID   int64          `gorm:"column:product_id" json:"product_id"`
	Locale      string         `gorm:"column:locale;not null;default:en" json:"locale"`
	Name        string         `gorm:"column:name;not null" json:"name"`
	Description string         `gorm:"column:description;not null" json:"description"`
	DeletedAt   gorm.DeletedAt `gorm:"column:deleted_at" json:"deleted_at"`
	CreatedAt   time.Time      `gorm:"column:created_at" json:"created_at"`
	UpdatedAt   time.Time      `gorm:"column:updated_at" json:"updated_at"`
}

// TableName PosProductsTranslation's table name
func (*PosProductsTranslation) TableName() string {
	return TableNamePosProductsTranslation
}
