// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package entity

import (
	"time"

	"gorm.io/gorm"
)

const TableNamePosCategory = "pos_categories"

// PosCategory mapped from table <pos_categories>
type PosCategory struct {
	ID          int64          `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	UUID        string         `gorm:"column:uuid;not null" json:"uuid"`
	Name        string         `gorm:"column:name;not null" json:"name"`
	DeletedAt   gorm.DeletedAt `gorm:"column:deleted_at" json:"deleted_at"`
	CreatedAt   time.Time      `gorm:"column:created_at" json:"created_at"`
	UpdatedAt   time.Time      `gorm:"column:updated_at" json:"updated_at"`
	StoreID     int64          `gorm:"column:store_id;not null;default:1" json:"store_id"`
	Status      bool           `gorm:"column:status;not null;default:1" json:"status"`
	Sequence    int32          `gorm:"column:sequence" json:"sequence"`
	Description string         `gorm:"column:description;not null;default:These are tasty things that you might want to try" json:"description"`
}

// TableName PosCategory's table name
func (*PosCategory) TableName() string {
	return TableNamePosCategory
}
