// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package entity

import (
	"time"

	"gorm.io/gorm"
)

const TableNamePosCustomerOrder = "pos_customer_orders"

// PosCustomerOrder mapped from table <pos_customer_orders>
type PosCustomerOrder struct {
	ID             int64          `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	SessionUUID    string         `gorm:"column:session_uuid" json:"session_uuid"`
	UUID           string         `gorm:"column:uuid;not null" json:"uuid"`
	Type           string         `gorm:"column:type;not null;default:pickup" json:"type"`
	Status         string         `gorm:"column:status;not null;default:pending" json:"status"`
	FirstName      string         `gorm:"column:first_name" json:"first_name"`
	LastName       string         `gorm:"column:last_name" json:"last_name"`
	ContactTel     string         `gorm:"column:contact_tel" json:"contact_tel"`
	ContactEmail   string         `gorm:"column:contact_email" json:"contact_email"`
	Remark         string         `gorm:"column:remark" json:"remark"`
	CreatedBy      int64          `gorm:"column:created_by" json:"created_by"`
	PendingBefore  time.Time      `gorm:"column:pending_before" json:"pending_before"`
	DeletedAt      gorm.DeletedAt `gorm:"column:deleted_at" json:"deleted_at"`
	CreatedAt      time.Time      `gorm:"column:created_at" json:"created_at"`
	UpdatedAt      time.Time      `gorm:"column:updated_at" json:"updated_at"`
	PaymentIntent  string         `gorm:"column:payment_intent" json:"payment_intent"`
	DisplayID      string         `gorm:"column:display_id" json:"display_id"`
	DeliveryTypeID int32          `gorm:"column:delivery_type_id" json:"delivery_type_id"`
}

// TableName PosCustomerOrder's table name
func (*PosCustomerOrder) TableName() string {
	return TableNamePosCustomerOrder
}
