// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package entity

import (
	"time"

	"gorm.io/gorm"
)

const TableNamePosProduct = "pos_products"

// PosProduct mapped from table <pos_products>
type PosProduct struct {
	ID                  int64          `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	UUID                string         `gorm:"column:uuid;not null" json:"uuid"`
	StoreID             int64          `gorm:"column:store_id;not null" json:"store_id"`
	Type                string         `gorm:"column:type;not null;default:Single" json:"type"`
	Status              string         `gorm:"column:status;not null;default:Active" json:"status"`
	Name                string         `gorm:"column:name;not null" json:"name"`
	Sku                 string         `gorm:"column:sku" json:"sku"`
	Description         string         `gorm:"column:description" json:"description"`
	SimplifiedName      string         `gorm:"column:simplified_name" json:"simplified_name"`
	PreviewURL          string         `gorm:"column:preview_url" json:"preview_url"`
	Price               float64        `gorm:"column:price;not null;default:0.00" json:"price"`
	PosProductTypeID    int64          `gorm:"column:pos_product_type_id;not null" json:"pos_product_type_id"`
	PosSubProductTypeID int64          `gorm:"column:pos_sub_product_type_id" json:"pos_sub_product_type_id"`
	PosCategoryID       int64          `gorm:"column:pos_category_id" json:"pos_category_id"`
	PrintToStation      bool           `gorm:"column:print_to_station;not null" json:"print_to_station"`
	PosKitchenStationID int64          `gorm:"column:pos_kitchen_station_id" json:"pos_kitchen_station_id"`
	DeletedAt           gorm.DeletedAt `gorm:"column:deleted_at" json:"deleted_at"`
	CreatedAt           time.Time      `gorm:"column:created_at" json:"created_at"`
	UpdatedAt           time.Time      `gorm:"column:updated_at" json:"updated_at"`
	DineinPrice         float64        `gorm:"column:dinein_price" json:"dinein_price"`
}

// TableName PosProduct's table name
func (*PosProduct) TableName() string {
	return TableNamePosProduct
}
