// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package entity

import (
	"time"

	"gorm.io/gorm"
)

const TableNamePosProductModifier = "pos_product_modifiers"

// PosProductModifier mapped from table <pos_product_modifiers>
type PosProductModifier struct {
	ID                      int64          `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	UUID                    string         `gorm:"column:uuid;not null" json:"uuid"`
	Name                    string         `gorm:"column:name;not null" json:"name"`
	AllowMultiple           bool           `gorm:"column:allow_multiple;not null;default:1" json:"allow_multiple"`
	DeletedAt               gorm.DeletedAt `gorm:"column:deleted_at" json:"deleted_at"`
	CreatedAt               time.Time      `gorm:"column:created_at" json:"created_at"`
	UpdatedAt               time.Time      `gorm:"column:updated_at" json:"updated_at"`
	StoreID                 int64          `gorm:"column:store_id;not null;default:1" json:"store_id"`
	PosProductID            int64          `gorm:"column:pos_product_id" json:"pos_product_id"`
	DefaultModifierOptionID int64          `gorm:"column:default_modifier_option_id" json:"default_modifier_option_id"`
	Type                    string         `gorm:"column:type" json:"type"`
	MinQty                  int32          `gorm:"column:min_qty" json:"min_qty"`
	MaxQty                  int32          `gorm:"column:max_qty" json:"max_qty"`
}

// TableName PosProductModifier's table name
func (*PosProductModifier) TableName() string {
	return TableNamePosProductModifier
}
