// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package entity

import (
	"time"

	"gorm.io/gorm"
)

const TableNamePosOrder = "pos_orders"

// PosOrder mapped from table <pos_orders>
type PosOrder struct {
	ID                 int64          `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	UUID               string         `gorm:"column:uuid;not null" json:"uuid"`
	DisplayID          string         `gorm:"column:display_id" json:"display_id"`
	TenantID           int64          `gorm:"column:tenant_id;not null" json:"tenant_id"`
	StoreID            int64          `gorm:"column:store_id;not null" json:"store_id"`
	Type               string         `gorm:"column:type;not null;default:pickup" json:"type"`
	Status             string         `gorm:"column:status;not null;default:pending" json:"status"`
	ContactTel         string         `gorm:"column:contact_tel" json:"contact_tel"`
	ContactEmail       string         `gorm:"column:contact_email" json:"contact_email"`
	Remark             string         `gorm:"column:remark" json:"remark"`
	CreatedBy          int64          `gorm:"column:created_by" json:"created_by"`
	ConfirmedAt        time.Time      `gorm:"column:confirmed_at" json:"confirmed_at"`
	ConfirmedBy        int64          `gorm:"column:confirmed_by" json:"confirmed_by"`
	DeletedAt          gorm.DeletedAt `gorm:"column:deleted_at" json:"deleted_at"`
	CreatedAt          time.Time      `gorm:"column:created_at" json:"created_at"`
	UpdatedAt          time.Time      `gorm:"column:updated_at" json:"updated_at"`
	FirstName          string         `gorm:"column:first_name" json:"first_name"`
	LastName           string         `gorm:"column:last_name" json:"last_name"`
	SessionUUID        string         `gorm:"column:session_uuid" json:"session_uuid"`
	PosCustomerOrderID int64          `gorm:"column:pos_customer_order_id" json:"pos_customer_order_id"`
	PendingBefore      time.Time      `gorm:"column:pending_before" json:"pending_before"`
}

// TableName PosOrder's table name
func (*PosOrder) TableName() string {
	return TableNamePosOrder
}
