// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package entity

import (
	"time"

	"gorm.io/gorm"
)

const TableNamePosMenuCategory = "pos_menu_categories"

// PosMenuCategory mapped from table <pos_menu_categories>
type PosMenuCategory struct {
	ID            int64          `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	UUID          string         `gorm:"column:uuid;not null" json:"uuid"`
	PosMenuID     int64          `gorm:"column:pos_menu_id;not null" json:"pos_menu_id"`
	PosCategoryID int64          `gorm:"column:pos_category_id;not null" json:"pos_category_id"`
	DeletedAt     gorm.DeletedAt `gorm:"column:deleted_at" json:"deleted_at"`
	CreatedAt     time.Time      `gorm:"column:created_at" json:"created_at"`
	UpdatedAt     time.Time      `gorm:"column:updated_at" json:"updated_at"`
}

// TableName PosMenuCategory's table name
func (*PosMenuCategory) TableName() string {
	return TableNamePosMenuCategory
}
