// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package entity

import (
	"time"

	"gorm.io/gorm"
)

const TableNamePosProductTypesTranslation = "pos_product_types_translations"

// PosProductTypesTranslation mapped from table <pos_product_types_translations>
type PosProductTypesTranslation struct {
	ID            int64          `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	ProductTypeID int64          `gorm:"column:product_type_id" json:"product_type_id"`
	Locale        string         `gorm:"column:locale;not null;default:en" json:"locale"`
	Name          string         `gorm:"column:name;not null" json:"name"`
	DeletedAt     gorm.DeletedAt `gorm:"column:deleted_at" json:"deleted_at"`
	CreatedAt     time.Time      `gorm:"column:created_at" json:"created_at"`
	UpdatedAt     time.Time      `gorm:"column:updated_at" json:"updated_at"`
}

// TableName PosProductTypesTranslation's table name
func (*PosProductTypesTranslation) TableName() string {
	return TableNamePosProductTypesTranslation
}
