// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package entity

import (
	"time"
)

const TableNamePosCartItem = "pos_cart_items"

// PosCartItem mapped from table <pos_cart_items>
type PosCartItem struct {
	ID           int64     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	UUID         string    `gorm:"column:uuid;not null" json:"uuid"`
	PosCartID    int64     `gorm:"column:pos_cart_id" json:"pos_cart_id"`
	PosProductID int64     `gorm:"column:pos_product_id;not null" json:"pos_product_id"`
	Remark       string    `gorm:"column:remark" json:"remark"`
	ExtraData    string    `gorm:"column:extra_data" json:"extra_data"`
	Qty          int32     `gorm:"column:qty;not null;default:1" json:"qty"`
	Price        float64   `gorm:"column:price;not null;default:0.00" json:"price"`
	CreatedAt    time.Time `gorm:"column:created_at" json:"created_at"`
	UpdatedAt    time.Time `gorm:"column:updated_at" json:"updated_at"`
}

// TableName PosCartItem's table name
func (*PosCartItem) TableName() string {
	return TableNamePosCartItem
}
