// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package entity

import (
	"time"

	"gorm.io/gorm"
)

const TableNamePosKitchenStation = "pos_kitchen_stations"

// PosKitchenStation mapped from table <pos_kitchen_stations>
type PosKitchenStation struct {
	ID          int64          `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	UUID        string         `gorm:"column:uuid;not null" json:"uuid"`
	TenantID    int64          `gorm:"column:tenant_id;not null" json:"tenant_id"`
	StoreID     int64          `gorm:"column:store_id;not null" json:"store_id"`
	Name        string         `gorm:"column:name;not null" json:"name"`
	DeletedAt   gorm.DeletedAt `gorm:"column:deleted_at" json:"deleted_at"`
	CreatedAt   time.Time      `gorm:"column:created_at" json:"created_at"`
	UpdatedAt   time.Time      `gorm:"column:updated_at" json:"updated_at"`
	Type        string         `gorm:"column:type;not null;default:kitchen" json:"type"`
	ConnType    string         `gorm:"column:conn_type" json:"conn_type"`
	ConnData    string         `gorm:"column:conn_data" json:"conn_data"`
	CreatedBy   int64          `gorm:"column:created_by" json:"created_by"`
	KitchenName string         `gorm:"column:kitchen_name" json:"kitchen_name"`
}

// TableName PosKitchenStation's table name
func (*PosKitchenStation) TableName() string {
	return TableNamePosKitchenStation
}
