// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package entity

import (
	"time"

	"gorm.io/gorm"
)

const TableNamePosProductComboOption = "pos_product_combo_options"

// PosProductComboOption mapped from table <pos_product_combo_options>
type PosProductComboOption struct {
	ID                  int64          `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	UUID                string         `gorm:"column:uuid;not null" json:"uuid"`
	PosProductID        int64          `gorm:"column:pos_product_id;not null" json:"pos_product_id"`
	Name                string         `gorm:"column:name;not null" json:"name"`
	MinQty              int32          `gorm:"column:min_qty;not null;default:1" json:"min_qty"`
	MaxQty              int32          `gorm:"column:max_qty;default:1" json:"max_qty"`
	DefaultPosProductID int64          `gorm:"column:default_pos_product_id" json:"default_pos_product_id"`
	DeletedAt           gorm.DeletedAt `gorm:"column:deleted_at" json:"deleted_at"`
	CreatedAt           time.Time      `gorm:"column:created_at" json:"created_at"`
	UpdatedAt           time.Time      `gorm:"column:updated_at" json:"updated_at"`
}

// TableName PosProductComboOption's table name
func (*PosProductComboOption) TableName() string {
	return TableNamePosProductComboOption
}
