// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package entity

import (
	"time"

	"gorm.io/gorm"
)

const TableNamePurchaseRequestItem = "purchase_request_items"

// PurchaseRequestItem mapped from table <purchase_request_items>
type PurchaseRequestItem struct {
	ID                int64          `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	PurchaseRequestID int64          `gorm:"column:purchase_request_id;not null" json:"purchase_request_id"`
	RawMaterialID     int64          `gorm:"column:raw_material_id" json:"raw_material_id"`
	Qty               float64        `gorm:"column:qty;not null" json:"qty"`
	Remark            string         `gorm:"column:remark" json:"remark"`
	Status            string         `gorm:"column:status;not null;default:pending" json:"status"`
	CreatedBy         int64          `gorm:"column:created_by" json:"created_by"`
	CreatedAt         time.Time      `gorm:"column:created_at" json:"created_at"`
	UpdatedAt         time.Time      `gorm:"column:updated_at" json:"updated_at"`
	DeletedAt         gorm.DeletedAt `gorm:"column:deleted_at" json:"deleted_at"`
}

// TableName PurchaseRequestItem's table name
func (*PurchaseRequestItem) TableName() string {
	return TableNamePurchaseRequestItem
}
