// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package entity

import (
	"time"

	"gorm.io/gorm"
)

const TableNamePurchaseOrderPurchaseRequest = "purchase_order_purchase_request"

// PurchaseOrderPurchaseRequest mapped from table <purchase_order_purchase_request>
type PurchaseOrderPurchaseRequest struct {
	ID                int64          `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	PurchaseOrderID   int64          `gorm:"column:purchase_order_id" json:"purchase_order_id"`
	PurchaseRequestID int64          `gorm:"column:purchase_request_id" json:"purchase_request_id"`
	DeletedAt         gorm.DeletedAt `gorm:"column:deleted_at" json:"deleted_at"`
	CreatedAt         time.Time      `gorm:"column:created_at" json:"created_at"`
	UpdatedAt         time.Time      `gorm:"column:updated_at" json:"updated_at"`
}

// TableName PurchaseOrderPurchaseRequest's table name
func (*PurchaseOrderPurchaseRequest) TableName() string {
	return TableNamePurchaseOrderPurchaseRequest
}
