// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package entity

import (
	"time"

	"gorm.io/gorm"
)

const TableNamePurchaseRequest = "purchase_requests"

// PurchaseRequest mapped from table <purchase_requests>
type PurchaseRequest struct {
	ID                int64          `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	UUID              string         `gorm:"column:uuid;not null" json:"uuid"`
	DisplayID         string         `gorm:"column:display_id" json:"display_id"`
	Status            string         `gorm:"column:status" json:"status"`
	StoreID           int64          `gorm:"column:store_id" json:"store_id"`
	TargetRestockDate time.Time      `gorm:"column:target_restock_date" json:"target_restock_date"`
	Remark            string         `gorm:"column:remark" json:"remark"`
	CreatedBy         int64          `gorm:"column:created_by" json:"created_by"`
	SubmittedBy       int64          `gorm:"column:submitted_by" json:"submitted_by"`
	ConfirmedBy       int64          `gorm:"column:confirmed_by" json:"confirmed_by"`
	CompletedBy       int64          `gorm:"column:completed_by" json:"completed_by"`
	ConfirmedAt       time.Time      `gorm:"column:confirmed_at" json:"confirmed_at"`
	CompletedAt       time.Time      `gorm:"column:completed_at" json:"completed_at"`
	SubmittedAt       time.Time      `gorm:"column:submitted_at" json:"submitted_at"`
	CreatedAt         time.Time      `gorm:"column:created_at" json:"created_at"`
	UpdatedAt         time.Time      `gorm:"column:updated_at" json:"updated_at"`
	DeletedAt         gorm.DeletedAt `gorm:"column:deleted_at" json:"deleted_at"`
	TenantID          int64          `gorm:"column:tenant_id" json:"tenant_id"`
}

// TableName PurchaseRequest's table name
func (*PurchaseRequest) TableName() string {
	return TableNamePurchaseRequest
}
