// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package entity

import (
	"time"

	"gorm.io/gorm"
)

const TableNameRawMaterialScheduledPrice = "raw_material_scheduled_prices"

// RawMaterialScheduledPrice mapped from table <raw_material_scheduled_prices>
type RawMaterialScheduledPrice struct {
	ID            int64          `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	UUID          string         `gorm:"column:uuid;not null" json:"uuid"`
	RawMaterialID int64          `gorm:"column:raw_material_id;not null" json:"raw_material_id"`
	StartDate     time.Time      `gorm:"column:start_date;not null" json:"start_date"`
	Price         float64        `gorm:"column:price;not null;default:0.00" json:"price"`
	CreatedBy     int64          `gorm:"column:created_by" json:"created_by"`
	DeletedAt     gorm.DeletedAt `gorm:"column:deleted_at" json:"deleted_at"`
	CreatedAt     time.Time      `gorm:"column:created_at" json:"created_at"`
	UpdatedAt     time.Time      `gorm:"column:updated_at" json:"updated_at"`
}

// TableName RawMaterialScheduledPrice's table name
func (*RawMaterialScheduledPrice) TableName() string {
	return TableNameRawMaterialScheduledPrice
}
