// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package entity

import (
	"time"
)

const TableNameRawMaterialStore = "raw_material_stores"

// RawMaterialStore mapped from table <raw_material_stores>
type RawMaterialStore struct {
	ID            int64     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	RawMaterialID int64     `gorm:"column:raw_material_id;not null" json:"raw_material_id"`
	StoreID       int64     `gorm:"column:store_id;not null" json:"store_id"`
	CreatedAt     time.Time `gorm:"column:created_at" json:"created_at"`
	UpdatedAt     time.Time `gorm:"column:updated_at" json:"updated_at"`
}

// TableName RawMaterialStore's table name
func (*RawMaterialStore) TableName() string {
	return TableNameRawMaterialStore
}
