// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package entity

import (
	"time"

	"gorm.io/gorm"
)

const TableNameRawMaterial = "raw_materials"

// RawMaterial mapped from table <raw_materials>
type RawMaterial struct {
	ID           int64          `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	UUID         string         `gorm:"column:uuid;not null" json:"uuid"`
	Sku          string         `gorm:"column:sku;not null" json:"sku"`
	NameEng      string         `gorm:"column:name_eng" json:"name_eng"`
	NameChin     string         `gorm:"column:name_chin" json:"name_chin"`
	UpdatedBy    int64          `gorm:"column:updated_by" json:"updated_by"`
	DeletedAt    gorm.DeletedAt `gorm:"column:deleted_at" json:"deleted_at"`
	CreatedAt    time.Time      `gorm:"column:created_at" json:"created_at"`
	UpdatedAt    time.Time      `gorm:"column:updated_at" json:"updated_at"`
	Unit         string         `gorm:"column:unit" json:"unit"`
	SupplierID   int64          `gorm:"column:supplier_id" json:"supplier_id"`
	Packing      string         `gorm:"column:packing" json:"packing"`
	DefaultPrice float64        `gorm:"column:default_price" json:"default_price"`
	TenantID     int64          `gorm:"column:tenant_id" json:"tenant_id"`
	Active       bool           `gorm:"column:active;not null;default:1" json:"active"`
	SubUnit      string         `gorm:"column:sub_unit" json:"sub_unit"`
	SubUnitQty   float64        `gorm:"column:sub_unit_qty;not null;default:1.00" json:"sub_unit_qty"`
}

// TableName RawMaterial's table name
func (*RawMaterial) TableName() string {
	return TableNameRawMaterial
}
