// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package entity

import (
	"time"
)

const TableNameRawMaterialCategory = "raw_material_category"

// RawMaterialCategory mapped from table <raw_material_category>
type RawMaterialCategory struct {
	ID            int64     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	RawMaterialID int64     `gorm:"column:raw_material_id" json:"raw_material_id"`
	CategoryID    int64     `gorm:"column:category_id" json:"category_id"`
	CreatedAt     time.Time `gorm:"column:created_at" json:"created_at"`
	UpdatedAt     time.Time `gorm:"column:updated_at" json:"updated_at"`
}

// TableName RawMaterialCategory's table name
func (*RawMaterialCategory) TableName() string {
	return TableNameRawMaterialCategory
}
