// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package entity

import (
	"time"

	"gorm.io/gorm"
)

const TableNameRoleUser = "role_user"

// RoleUser mapped from table <role_user>
type RoleUser struct {
	ID        int32          `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	RoleID    int32          `gorm:"column:role_id;not null" json:"role_id"`
	UserID    int64          `gorm:"column:user_id;not null" json:"user_id"`
	CreatedAt time.Time      `gorm:"column:created_at" json:"created_at"`
	UpdatedAt time.Time      `gorm:"column:updated_at" json:"updated_at"`
	DeletedAt gorm.DeletedAt `gorm:"column:deleted_at" json:"deleted_at"`
}

// TableName RoleUser's table name
func (*RoleUser) TableName() string {
	return TableNameRoleUser
}
