// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package entity

import (
	"time"

	"gorm.io/gorm"
)

const TableNameRosterConfirmation = "roster_confirmations"

// RosterConfirmation mapped from table <roster_confirmations>
type RosterConfirmation struct {
	ID        int64          `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Date      time.Time      `gorm:"column:date;not null" json:"date"`
	StoreID   int64          `gorm:"column:store_id;not null" json:"store_id"`
	CreatedBy int64          `gorm:"column:created_by" json:"created_by"`
	CreatedAt time.Time      `gorm:"column:created_at" json:"created_at"`
	UpdatedAt time.Time      `gorm:"column:updated_at" json:"updated_at"`
	DeletedAt gorm.DeletedAt `gorm:"column:deleted_at" json:"deleted_at"`
	Status    string         `gorm:"column:status;not null;default:confirmed" json:"status"`
}

// TableName RosterConfirmation's table name
func (*RosterConfirmation) TableName() string {
	return TableNameRosterConfirmation
}
