// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package entity

import (
	"time"

	"gorm.io/gorm"
)

const TableNameShift = "shifts"

// Shift mapped from table <shifts>
type Shift struct {
	ID        int64          `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	UUID      string         `gorm:"column:uuid;not null" json:"uuid"`
	Name      string         `gorm:"column:name" json:"name"`
	FromHour  int32          `gorm:"column:from_hour;not null" json:"from_hour"`
	FromMin   int32          `gorm:"column:from_min;not null" json:"from_min"`
	ToHour    int32          `gorm:"column:to_hour;not null" json:"to_hour"`
	ToMin     int32          `gorm:"column:to_min;not null" json:"to_min"`
	CreatedAt time.Time      `gorm:"column:created_at" json:"created_at"`
	UpdatedAt time.Time      `gorm:"column:updated_at" json:"updated_at"`
	DeletedAt gorm.DeletedAt `gorm:"column:deleted_at" json:"deleted_at"`
	RoleID    int32          `gorm:"column:role_id" json:"role_id"`
	TenantID  int64          `gorm:"column:tenant_id" json:"tenant_id"`
}

// TableName Shift's table name
func (*Shift) TableName() string {
	return TableNameShift
}
