// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package entity

import (
	"time"
)

const TableNameStoreOtpLog = "store_otp_logs"

// StoreOtpLog mapped from table <store_otp_logs>
type StoreOtpLog struct {
	ID        int64     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Otp       string    `gorm:"column:otp;not null" json:"otp"`
	PrevOtp   string    `gorm:"column:prev_otp" json:"prev_otp"`
	StoreID   int64     `gorm:"column:store_id;not null" json:"store_id"`
	Trace     string    `gorm:"column:trace" json:"trace"`
	CreatedAt time.Time `gorm:"column:created_at" json:"created_at"`
	UpdatedAt time.Time `gorm:"column:updated_at" json:"updated_at"`
}

// TableName StoreOtpLog's table name
func (*StoreOtpLog) TableName() string {
	return TableNameStoreOtpLog
}
