// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package entity

import (
	"time"

	"gorm.io/gorm"
)

const TableNameStoreProduct = "store_products"

// StoreProduct mapped from table <store_products>
type StoreProduct struct {
	ID        int64          `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	UUID      string         `gorm:"column:uuid;not null" json:"uuid"`
	Name      string         `gorm:"column:name" json:"name"`
	StoreID   int64          `gorm:"column:store_id;not null" json:"store_id"`
	Price     float64        `gorm:"column:price;not null;default:0.00" json:"price"`
	DeletedAt gorm.DeletedAt `gorm:"column:deleted_at" json:"deleted_at"`
	CreatedAt time.Time      `gorm:"column:created_at" json:"created_at"`
	UpdatedAt time.Time      `gorm:"column:updated_at" json:"updated_at"`
}

// TableName StoreProduct's table name
func (*StoreProduct) TableName() string {
	return TableNameStoreProduct
}
