// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package entity

import (
	"time"

	"gorm.io/gorm"
)

const TableNameStoreTranslation = "store_translations"

// StoreTranslation mapped from table <store_translations>
type StoreTranslation struct {
	ID          int64          `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	StoreID     int64          `gorm:"column:store_id" json:"store_id"`
	Locale      string         `gorm:"column:locale;not null;default:en" json:"locale"`
	Name        string         `gorm:"column:name;not null" json:"name"`
	Banner      string         `gorm:"column:banner" json:"banner"`
	Description string         `gorm:"column:description" json:"description"`
	DeletedAt   gorm.DeletedAt `gorm:"column:deleted_at" json:"deleted_at"`
	CreatedAt   time.Time      `gorm:"column:created_at" json:"created_at"`
	UpdatedAt   time.Time      `gorm:"column:updated_at" json:"updated_at"`
}

// TableName StoreTranslation's table name
func (*StoreTranslation) TableName() string {
	return TableNameStoreTranslation
}
