// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package entity

import (
	"time"
)

const TableNameStoreSale = "store_sales"

// StoreSale mapped from table <store_sales>
type StoreSale struct {
	ID            int64     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	StoreID       int64     `gorm:"column:store_id;not null" json:"store_id"`
	SalesDate     time.Time `gorm:"column:sales_date;not null" json:"sales_date"`
	Type          string    `gorm:"column:type;not null" json:"type"`
	EstimatedSale float64   `gorm:"column:estimated_sale" json:"estimated_sale"`
	ActualSale    float64   `gorm:"column:actual_sale" json:"actual_sale"`
	CreatedAt     time.Time `gorm:"column:created_at" json:"created_at"`
	UpdatedAt     time.Time `gorm:"column:updated_at" json:"updated_at"`
}

// TableName StoreSale's table name
func (*StoreSale) TableName() string {
	return TableNameStoreSale
}
