// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package entity

import (
	"time"

	"gorm.io/gorm"
)

const TableNameStoreProductRawMaterial = "store_product_raw_materials"

// StoreProductRawMaterial mapped from table <store_product_raw_materials>
type StoreProductRawMaterial struct {
	ID             int64          `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	UUID           string         `gorm:"column:uuid;not null" json:"uuid"`
	StoreProductID int64          `gorm:"column:store_product_id;not null" json:"store_product_id"`
	RawMaterialID  int64          `gorm:"column:raw_material_id;not null" json:"raw_material_id"`
	PercentageOf   float64        `gorm:"column:percentageOf;not null;default:0.00" json:"percentageOf"`
	DeletedAt      gorm.DeletedAt `gorm:"column:deleted_at" json:"deleted_at"`
	CreatedAt      time.Time      `gorm:"column:created_at" json:"created_at"`
	UpdatedAt      time.Time      `gorm:"column:updated_at" json:"updated_at"`
}

// TableName StoreProductRawMaterial's table name
func (*StoreProductRawMaterial) TableName() string {
	return TableNameStoreProductRawMaterial
}
