// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package entity

import (
	"time"
)

const TableNameStoreDeliveryType = "store_delivery_types"

// StoreDeliveryType mapped from table <store_delivery_types>
type StoreDeliveryType struct {
	ID             int64     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	StoreID        int64     `gorm:"column:store_id;not null" json:"store_id"`
	DeliveryTypeID int32     `gorm:"column:delivery_type_id;not null" json:"delivery_type_id"`
	CreatedAt      time.Time `gorm:"column:created_at" json:"created_at"`
	UpdatedAt      time.Time `gorm:"column:updated_at" json:"updated_at"`
}

// TableName StoreDeliveryType's table name
func (*StoreDeliveryType) TableName() string {
	return TableNameStoreDeliveryType
}
