// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package entity

import (
	"time"

	"gorm.io/gorm"
)

const TableNameStore = "stores"

// Store mapped from table <stores>
type Store struct {
	ID            int64          `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	UUID          string         `gorm:"column:uuid;not null" json:"uuid"`
	Name          string         `gorm:"column:name;not null" json:"name"`
	AuthCode      string         `gorm:"column:auth_code;not null" json:"auth_code"`
	CreatedAt     time.Time      `gorm:"column:created_at" json:"created_at"`
	UpdatedAt     time.Time      `gorm:"column:updated_at" json:"updated_at"`
	Otp           string         `gorm:"column:otp" json:"otp"`
	OtpValidUntil time.Time      `gorm:"column:otp_valid_until" json:"otp_valid_until"`
	DeletedAt     gorm.DeletedAt `gorm:"column:deleted_at" json:"deleted_at"`
	TenantID      int64          `gorm:"column:tenant_id" json:"tenant_id"`
	WarehouseID   int64          `gorm:"column:warehouse_id" json:"warehouse_id"`
	Logo          string         `gorm:"column:logo" json:"logo"`
	Banner        string         `gorm:"column:banner" json:"banner"`
	Description   string         `gorm:"column:description" json:"description"`
	PreviewURL    string         `gorm:"column:preview_url" json:"preview_url"`
	OnlineUntil   time.Time      `gorm:"column:online_until" json:"online_until"`
	Cuisine       string         `gorm:"column:cuisine" json:"cuisine"`
	OrderPrefix   string         `gorm:"column:order_prefix" json:"order_prefix"`
}

// TableName Store's table name
func (*Store) TableName() string {
	return TableNameStore
}
