// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package entity

import (
	"time"

	"gorm.io/gorm"
)

const TableNameUser = "users"

// User mapped from table <users>
type User struct {
	ID                 int64          `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	UUID               string         `gorm:"column:uuid;not null" json:"uuid"`
	Name               string         `gorm:"column:name;not null" json:"name"`
	Email              string         `gorm:"column:email" json:"email"`
	EmailVerifiedAt    time.Time      `gorm:"column:email_verified_at" json:"email_verified_at"`
	Password           string         `gorm:"column:password;not null" json:"password"`
	DeletedAt          gorm.DeletedAt `gorm:"column:deleted_at" json:"deleted_at"`
	RememberToken      string         `gorm:"column:remember_token" json:"remember_token"`
	CreatedAt          time.Time      `gorm:"column:created_at" json:"created_at"`
	UpdatedAt          time.Time      `gorm:"column:updated_at" json:"updated_at"`
	MonthlySalary      float64        `gorm:"column:monthly_salary" json:"monthly_salary"`
	WorkingHoursPerDay int32          `gorm:"column:working_hours_per_day;default:10" json:"working_hours_per_day"`
	HourlyWage         float64        `gorm:"column:hourly_wage" json:"hourly_wage"`
	Hkid               string         `gorm:"column:hkid" json:"hkid"`
	Tel                string         `gorm:"column:tel" json:"tel"`
	JoiningDate        string         `gorm:"column:joining_date" json:"joining_date"`
	Active             int32          `gorm:"column:active;not null;default:1" json:"active"`
	TenantID           int64          `gorm:"column:tenant_id" json:"tenant_id"`
	IsHeadOffice       bool           `gorm:"column:is_head_office;not null" json:"is_head_office"`
}

// TableName User's table name
func (*User) TableName() string {
	return TableNameUser
}
