// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package entity

import (
	"time"

	"gorm.io/gorm"
)

const TableNameUserLeaveHistory = "user_leave_history"

// UserLeaveHistory mapped from table <user_leave_history>
type UserLeaveHistory struct {
	ID         int64          `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	UUID       string         `gorm:"column:uuid;not null" json:"uuid"`
	DateFrom   time.Time      `gorm:"column:date_from;not null" json:"date_from"`
	DateTo     time.Time      `gorm:"column:date_to;not null" json:"date_to"`
	Periodfrom string         `gorm:"column:periodfrom;not null;default:AM" json:"periodfrom"`
	Periodto   string         `gorm:"column:periodto;not null;default:PM" json:"periodto"`
	Total      float64        `gorm:"column:total;not null" json:"total"`
	Status     string         `gorm:"column:status;not null" json:"status"`
	Remark     string         `gorm:"column:remark;not null" json:"remark"`
	UserID     int64          `gorm:"column:user_id;not null" json:"user_id"`
	LeaveID    int64          `gorm:"column:leave_id;not null" json:"leave_id"`
	DeletedAt  gorm.DeletedAt `gorm:"column:deleted_at" json:"deleted_at"`
	CreatedAt  time.Time      `gorm:"column:created_at" json:"created_at"`
	UpdatedAt  time.Time      `gorm:"column:updated_at" json:"updated_at"`
	Type       string         `gorm:"column:type;default:history" json:"type"`
}

// TableName UserLeaveHistory's table name
func (*UserLeaveHistory) TableName() string {
	return TableNameUserLeaveHistory
}
