// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package entity

import (
	"time"

	"gorm.io/gorm"
)

const TableNameUserLeaveHistoryAttachment = "user_leave_history_attachments"

// UserLeaveHistoryAttachment mapped from table <user_leave_history_attachments>
type UserLeaveHistoryAttachment struct {
	ID             int64          `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	LeaveHistoryID int64          `gorm:"column:leave_history_id" json:"leave_history_id"`
	URL            string         `gorm:"column:url;not null" json:"url"`
	DeletedAt      gorm.DeletedAt `gorm:"column:deleted_at" json:"deleted_at"`
	CreatedAt      time.Time      `gorm:"column:created_at" json:"created_at"`
	UpdatedAt      time.Time      `gorm:"column:updated_at" json:"updated_at"`
}

// TableName UserLeaveHistoryAttachment's table name
func (*UserLeaveHistoryAttachment) TableName() string {
	return TableNameUserLeaveHistoryAttachment
}
