// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package entity

import (
	"time"

	"gorm.io/gorm"
)

const TableNameWarehouseArea = "warehouse_areas"

// WarehouseArea mapped from table <warehouse_areas>
type WarehouseArea struct {
	ID          int64          `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	WarehouseID int64          `gorm:"column:warehouse_id;not null" json:"warehouse_id"`
	TenantID    int64          `gorm:"column:tenant_id" json:"tenant_id"`
	UUID        string         `gorm:"column:uuid;not null" json:"uuid"`
	Name        string         `gorm:"column:name;not null" json:"name"`
	QrCode      string         `gorm:"column:qr_code;not null" json:"qr_code"`
	DeletedAt   gorm.DeletedAt `gorm:"column:deleted_at" json:"deleted_at"`
	CreatedAt   time.Time      `gorm:"column:created_at" json:"created_at"`
	UpdatedAt   time.Time      `gorm:"column:updated_at" json:"updated_at"`
}

// TableName WarehouseArea's table name
func (*WarehouseArea) TableName() string {
	return TableNameWarehouseArea
}
