// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package entity

import (
	"time"

	"gorm.io/gorm"
)

const TableNameWarehouseRecord = "warehouse_records"

// WarehouseRecord mapped from table <warehouse_records>
type WarehouseRecord struct {
	ID              int64          `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	UUID            string         `gorm:"column:uuid;not null" json:"uuid"`
	WarehouseID     int64          `gorm:"column:warehouse_id;not null" json:"warehouse_id"`
	WarehouseAreaID int64          `gorm:"column:warehouse_area_id;not null" json:"warehouse_area_id"`
	RawMaterialID   int64          `gorm:"column:raw_material_id;not null" json:"raw_material_id"`
	Action          string         `gorm:"column:action;not null" json:"action"`
	Qty             float64        `gorm:"column:qty;not null;default:0.00" json:"qty"`
	Remark          string         `gorm:"column:remark" json:"remark"`
	UpdatedBy       int64          `gorm:"column:updated_by;not null" json:"updated_by"`
	DeletedAt       gorm.DeletedAt `gorm:"column:deleted_at" json:"deleted_at"`
	CreatedAt       time.Time      `gorm:"column:created_at" json:"created_at"`
	UpdatedAt       time.Time      `gorm:"column:updated_at" json:"updated_at"`
}

// TableName WarehouseRecord's table name
func (*WarehouseRecord) TableName() string {
	return TableNameWarehouseRecord
}
