// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package entity

import (
	"time"
)

const TableNameWarehouseAreaRawMaterial = "warehouse_area_raw_materials"

// WarehouseAreaRawMaterial mapped from table <warehouse_area_raw_materials>
type WarehouseAreaRawMaterial struct {
	ID              int64     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	UUID            string    `gorm:"column:uuid;not null" json:"uuid"`
	WarehouseAreaID int64     `gorm:"column:warehouse_area_id;not null" json:"warehouse_area_id"`
	RawMaterialID   int64     `gorm:"column:raw_material_id;not null" json:"raw_material_id"`
	CreatedAt       time.Time `gorm:"column:created_at" json:"created_at"`
	UpdatedAt       time.Time `gorm:"column:updated_at" json:"updated_at"`
	Qty             float64   `gorm:"column:qty;not null;default:0.00" json:"qty"`
}

// TableName WarehouseAreaRawMaterial's table name
func (*WarehouseAreaRawMaterial) TableName() string {
	return TableNameWarehouseAreaRawMaterial
}
