// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package entity

import (
	"time"
)

const TableNameWarehouseAllowedRawMaterial = "warehouse_allowed_raw_materials"

// WarehouseAllowedRawMaterial mapped from table <warehouse_allowed_raw_materials>
type WarehouseAllowedRawMaterial struct {
	ID            int64     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	WarehouseID   int64     `gorm:"column:warehouse_id;not null" json:"warehouse_id"`
	RawMaterialID int64     `gorm:"column:raw_material_id;not null" json:"raw_material_id"`
	CreatedAt     time.Time `gorm:"column:created_at" json:"created_at"`
	UpdatedAt     time.Time `gorm:"column:updated_at" json:"updated_at"`
}

// TableName WarehouseAllowedRawMaterial's table name
func (*WarehouseAllowedRawMaterial) TableName() string {
	return TableNameWarehouseAllowedRawMaterial
}
