// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package entity

import (
	"time"

	"gorm.io/gorm"
)

const TableNameWarehouse = "warehouses"

// Warehouse mapped from table <warehouses>
type Warehouse struct {
	ID        int64          `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	UUID      string         `gorm:"column:uuid;not null" json:"uuid"`
	Name      string         `gorm:"column:name;not null" json:"name"`
	TenantID  int64          `gorm:"column:tenant_id" json:"tenant_id"`
	DeletedAt gorm.DeletedAt `gorm:"column:deleted_at" json:"deleted_at"`
	CreatedAt time.Time      `gorm:"column:created_at" json:"created_at"`
	UpdatedAt time.Time      `gorm:"column:updated_at" json:"updated_at"`
	IsHidden  bool           `gorm:"column:isHidden;not null" json:"isHidden"`
}

// TableName Warehouse's table name
func (*Warehouse) TableName() string {
	return TableNameWarehouse
}
